version: "3.9"

services:
  bss-workplace-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ompnw
    ports:
      - 8080:8080 # REST
      - 8082:8082 # gRPC
      - 9100:9100 # Metrics prometheus
      - 8000:8000 # Status prometheus
      - 40000:40000 # Debug port
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/live']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./migrations:/root/migrations
      - ./config.yml:/root/config.yml
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8081:8080
    restart: always
    volumes:
      - ./swagger:/swagger
    environment:
      #API_URL: http://0.0.0.0:8080
      SWAGGER_JSON: /swagger/ozonmp/bss_workplace_api/v1/bss_workplace_api.swagger.json
      #SUPPORTED_SUBMIT_METHODS: "get, put, post, delete, options, head", patch, trace"
    depends_on:
      - bss-workplace-api
    networks:
      - ompnw

networks:
  ompnw:
    driver: bridge
