# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/bss_workplace_api/v1/bss_workplace_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2


class BssWorkplaceApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def CreateWorkplaceV1(self, stream: 'grpclib.server.Stream[ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.CreateWorkplaceV1Request, ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.CreateWorkplaceV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def DescribeWorkplaceV1(self, stream: 'grpclib.server.Stream[ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.DescribeWorkplaceV1Request, ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.DescribeWorkplaceV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def ListWorkplaceV1(self, stream: 'grpclib.server.Stream[ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.ListWorkplaceV1Request, ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.ListWorkplaceV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveWorkplaceV1(self, stream: 'grpclib.server.Stream[ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.RemoveWorkplaceV1Request, ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.RemoveWorkplaceV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/CreateWorkplaceV1': grpclib.const.Handler(
                self.CreateWorkplaceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.CreateWorkplaceV1Request,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.CreateWorkplaceV1Response,
            ),
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/DescribeWorkplaceV1': grpclib.const.Handler(
                self.DescribeWorkplaceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.DescribeWorkplaceV1Request,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.DescribeWorkplaceV1Response,
            ),
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/ListWorkplaceV1': grpclib.const.Handler(
                self.ListWorkplaceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.ListWorkplaceV1Request,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.ListWorkplaceV1Response,
            ),
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/RemoveWorkplaceV1': grpclib.const.Handler(
                self.RemoveWorkplaceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.RemoveWorkplaceV1Request,
                ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.RemoveWorkplaceV1Response,
            ),
        }


class BssWorkplaceApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateWorkplaceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/CreateWorkplaceV1',
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.CreateWorkplaceV1Request,
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.CreateWorkplaceV1Response,
        )
        self.DescribeWorkplaceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/DescribeWorkplaceV1',
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.DescribeWorkplaceV1Request,
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.DescribeWorkplaceV1Response,
        )
        self.ListWorkplaceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/ListWorkplaceV1',
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.ListWorkplaceV1Request,
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.ListWorkplaceV1Response,
        )
        self.RemoveWorkplaceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.bss_workplace_api.v1.BssWorkplaceApiService/RemoveWorkplaceV1',
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.RemoveWorkplaceV1Request,
            ozonmp.bss_workplace_api.v1.bss_workplace_api_pb2.RemoveWorkplaceV1Response,
        )
